export type SeoEntry={id:string;path:string;title:string;description:string;ogImage?:string;robots?:string;keywords?:string[]}

const OG='/images/background/background(17).webp'
const BRAND='KalambreStudio'
const BASE_KW=['KalambreStudio','AnderNikolay','Ander Nikolay','fotografía','fotógrafo','vídeo','producción audiovisual','estudio creativo','dirección de arte','branding','diseño','imagen de marca','contenido','marketing','publicidad','creación de contenidos','corporativo','retrato','producto','editorial','España','País Vasco','Gipuzkoa','Guipúzcoa','Bizkaia','Vizcaya','Irún','Irun','Bilbao','Donostia','San Sebastián','San Sebastian']

export const SEO_PAGES:SeoEntry[]=[
  {id:'home',path:'/',title:`${BRAND} | Estudio creativo de fotografía y vídeo`,description:`${BRAND} es el estudio creativo fundado por AnderNikolay, artista y fotógrafo. Producción de fotografía y vídeo, dirección de arte y contenido para marcas y proyectos culturales. Servicios corporativos de imagen de marca, diseño y comunicación visual. Trabajamos en España, especialmente en el País Vasco (Gipuzkoa y Bizkaia), entre Irún y Bilbao.`,ogImage:OG,keywords:[...BASE_KW,'estudio de fotografía','estudio de vídeo','dirección creativa','País Vasco']},
  {id:'arte',path:'/arte',title:`Arte | ${BRAND}`,description:`Proyectos artísticos de AnderNikolay en ${BRAND}: fotografía de autor, series editoriales, exploración visual y narrativa. Desarrollo de obra y comisiones artísticas con una estética contemporánea, cuidando concepto, luz y postproducción. Disponible para colaboraciones en Gipuzkoa, Bizkaia y el resto de España.`,ogImage:OG,keywords:[...BASE_KW,'arte','fotografía de autor','proyecto artístico','serie fotográfica']},
  {id:'diseno',path:'/diseno',title:`Diseño | ${BRAND}`,description:`Diseño para marcas y proyectos: identidad visual, sistemas gráficos, layouts y piezas digitales/impresas. En ${BRAND} unimos criterio artístico con enfoque corporativo para mejorar reconocimiento y coherencia visual. Servicio en País Vasco (Irún, Donostia, Bilbao) y España.`,ogImage:OG,keywords:[...BASE_KW,'diseño gráfico','identidad visual','sistema visual','piezas de marca']},
  {id:'marca',path:'/marca',title:`Imagen de marca | ${BRAND}`,description:`Estrategia y construcción de marca en ${BRAND}: posicionamiento visual, tono, dirección creativa y coherencia de contenidos. Ideal para empresas y proyectos que buscan una imagen sólida y contemporánea, combinando fotografía, vídeo y diseño. Cobertura principal en Gipuzkoa y Bizkaia, con disponibilidad en toda España.`,ogImage:OG,keywords:[...BASE_KW,'imagen de marca','estrategia de marca','posicionamiento','dirección creativa']},
  {id:'fotografia',path:'/fotografia',title:`Fotografía | ${BRAND}`,description:`Fotografía profesional y artística por AnderNikolay: retrato, corporativo, producto, editorial y campañas. Producción cuidada desde concepto a entrega final, con estética de estudio y narrativa de marca. Trabajo habitual entre Irún y Bilbao (Gipuzkoa y Bizkaia) y desplazamientos por España.`,ogImage:OG,keywords:[...BASE_KW,'fotografía corporativa','retrato','fotografía de producto','campaña','editorial']},
  {id:'video',path:'/video',title:`Vídeo | ${BRAND}`,description:`Producción de vídeo en ${BRAND}: piezas corporativas, contenido para redes, campañas y proyectos creativos. Dirección, rodaje y edición con enfoque cinematográfico, adaptado a objetivos de marca. Servicio en País Vasco (Gipuzkoa/Bizkaia) y en toda España.`,ogImage:OG,keywords:[...BASE_KW,'vídeo corporativo','reels','spot','edición de vídeo','rodaje']},
  {id:'marketing',path:'/marketing',title:`Marketing | ${BRAND}`,description:`Marketing y comunicación visual orientados a resultados: planificación de contenidos, campañas y piezas creativas coherentes con la marca. En ${BRAND} la estrategia se apoya en fotografía, vídeo y diseño para mejorar presencia y conversión. Trabajo en Gipuzkoa, Bizkaia y España.`,ogImage:OG,keywords:[...BASE_KW,'marketing digital','campañas','estrategia de contenidos','comunicación']},
  {id:'publicidad',path:'/publicidad',title:`Publicidad | ${BRAND}`,description:`Creatividad publicitaria en ${BRAND}: concepto, dirección de arte y producción de assets (foto/vídeo/diseño) para campañas. Enfoque premium y contemporáneo para marcas, negocios y proyectos culturales. Producción local entre Irún y Bilbao y disponibilidad en España.`,ogImage:OG,keywords:[...BASE_KW,'publicidad','campaña publicitaria','dirección de arte','producción']},
  {id:'branding',path:'/branding',title:`Branding | ${BRAND}`,description:`Branding completo: identidad, tono visual y sistema de contenido. ${BRAND} integra diseño, fotografía y vídeo para construir una marca consistente, reconocible y lista para crecer. Servicios corporativos y creativos en el País Vasco (Gipuzkoa/Bizkaia) y España.`,ogImage:OG,keywords:[...BASE_KW,'branding','identidad corporativa','logo','manual de marca']},
  {id:'creatividad',path:'/creatividad',title:`Creatividad | ${BRAND}`,description:`Dirección creativa y desarrollo de ideas: moodboards, concepto, narrativa y estética. En ${BRAND}, AnderNikolay lidera el proceso creativo para campañas, editoriales y contenido de marca, cuidando cada detalle desde preproducción a entrega final.`,ogImage:OG,keywords:[...BASE_KW,'dirección creativa','concepto','moodboard','narrativa visual']},
  {id:'contenido',path:'/contenido',title:`Contenido | ${BRAND}`,description:`Creación de contenido para marcas: fotografía, vídeo, piezas gráficas y storytelling visual para web y redes. Flujo de producción ágil y coherente con la identidad, pensado para escalar publicaciones sin perder calidad. Servicio en Gipuzkoa, Bizkaia y España.`,ogImage:OG,keywords:[...BASE_KW,'creación de contenido','contenido para redes','storytelling','contenido de marca']},
  {id:'redes',path:'/redes',title:`Redes | ${BRAND}`,description:`Contenido y piezas para redes sociales: formatos verticales, series, campañas y assets listos para publicar. En ${BRAND} trabajamos con una estética limpia y contemporánea, alineada con objetivos de marca y calendario de contenidos.`,ogImage:OG,keywords:[...BASE_KW,'redes sociales','reels','contenido vertical','calendario de contenidos']},
  {id:'digital',path:'/digital',title:`Digital | ${BRAND}`,description:`Presencia digital con identidad: creatividad y producción de assets para web, landing pages y campañas. ${BRAND} combina diseño, fotografía y vídeo para que la experiencia digital sea coherente, rápida y visualmente fuerte.`,ogImage:OG,keywords:[...BASE_KW,'web','landing','assets','contenido digital']},
  {id:'estudio',path:'/estudio',title:`Estudio | ${BRAND}`,description:`El estudio de ${BRAND}: producción creativa liderada por AnderNikolay. Fotografía y vídeo con dirección de arte, postproducción y cuidado técnico. Operamos principalmente en el País Vasco (Gipuzkoa/Bizkaia), entre Irún y Bilbao, con posibilidad de desplazamiento por España.`,ogImage:OG,keywords:[...BASE_KW,'estudio','producción','postproducción','equipo creativo']},
  {id:'portfolio',path:'/portfolio',title:`Portfolio | ${BRAND}`,description:`Portfolio de ${BRAND}: selección de fotografía, vídeo y proyectos de diseño/branding. Trabajos para marcas, proyectos corporativos y piezas artísticas, con enfoque contemporáneo y cuidado estético.`,ogImage:OG,keywords:[...BASE_KW,'portfolio','trabajos','casos','proyectos']},
  {id:'proyectos',path:'/proyectos',title:`Proyectos | ${BRAND}`,description:`Proyectos y colaboraciones de ${BRAND}: campañas, editoriales, identidad visual y producción audiovisual. Desde briefs corporativos hasta piezas artísticas, con un proceso claro y entregables listos para uso digital e impreso.`,ogImage:OG,keywords:[...BASE_KW,'proyectos','colaboraciones','campañas','producción creativa']},
  {id:'equipo',path:'/equipo',title:`Equipo | ${BRAND}`,description:`Equipo y dirección: ${BRAND} está fundado por AnderNikolay, artista y fotógrafo. Red de colaboradores según proyecto (producción, diseño, maquillaje, estilismo, etc.) para ofrecer entregas sólidas en fotografía, vídeo e identidad de marca.`,ogImage:OG,keywords:[...BASE_KW,'equipo','fundador','AnderNikolay','colaboradores']},
  {id:'contacto',path:'/contacto',title:`Contacto | ${BRAND}`,description:`Contacto ${BRAND}: cuéntanos tu proyecto de fotografía, vídeo, branding o diseño. Trabajamos en España, especialmente en el País Vasco (Gipuzkoa y Bizkaia), entre Irún y Bilbao. Respuesta rápida para presupuestos, disponibilidad y planificación.`,ogImage:OG,keywords:[...BASE_KW,'contacto','presupuesto','Gipuzkoa','Bizkaia','Irún','Bilbao']}
]
